format = """
[╭](fg:current_line)\
$os\
$directory\
$cmd_duration\
$shell\
$time\
$username\
$line_break\
$character\
"""

palette = 'cloudy'
add_newline = true

[palettes.cloudy]
foreground = '#ffffff'
background = '#1a1a1a'
current_line = '#4a4a4a'
primary = '#6a6a6a'
box = '#3a3a3a'
blue = '#b0b0b0'
cyan = '#d0d0d0'
green = '#c0c0c0'
orange = '#f0f0f0'
pink = '#e5e5e5'
purple = '#d5d5d5'
red = '#a0a0a0'
yellow = '#f8f8f8'

[os]
format = '(fg:current_line)[](fg:green)[$symbol ](fg:primary bg:green)[](fg:green)'
disabled = false

[os.symbols]
Alpine = ''
Amazon = ''
Android = ''
Arch = ''
CentOS = ''
Debian = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Linux = ''
Macos = ''
Manjaro = ''
Mariner = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = ''
OpenCloudOS = ''
openEuler = ''
openSUSE = ''
OracleLinux = '⊂⊃'
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = ''


[directory]
format = '[-](fg:current_line)[](fg:green)[ ](fg:primary bg:green)[](fg:green bg:box)[ $read_only$truncation_symbol$path](fg:foreground bg:box)[](fg:box)'
home_symbol = "󰉌 "
truncation_symbol = ' '
truncation_length = 2
read_only = '󱧴 '
read_only_style = ''

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
"dev" = "󰲋 "



[rust]
format = '[-](fg:current_line)[](fg:red)[$symbol](fg:primary bg:red)[](fg:red bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' Rust'



[cmd_duration]
min_time = 500
format = '[-](fg:current_line)[](fg:green)[ ](fg:primary bg:green)[](fg:green bg:box)[ $duration ](fg:foreground bg:box)[](fg:box)'

[shell]
format = '[-](fg:current_line)[](fg:green)[ ](fg:primary bg:green)[](fg:green bg:box)[ $indicator](fg:foreground bg:box)[](fg:box)'
unknown_indicator = 'shell'
powershell_indicator = 'powershell'
fish_indicator = 'fish'
disabled = false


[username]
format = '[-](fg:current_line)[](fg:green)[ ](fg:primary bg:green)[](fg:green bg:box)[ $user](fg:foreground bg:box)[](fg:box) '
show_always = true

[character]
format = """
[╰─$symbol](fg:current_line) """
success_symbol = '[❯](fg:bold green)'
error_symbol = '[×](fg:bold red)'
